# ==============================================================================
# FILE: hck_causelist_mailer.py
# DESCRIPTION: Secure Outbound Dispatch Component
# ------------------------------------------------------------------------------
# Parses runtime environmental variables and security parameters from your
# configuration matrix (hck_causelist_config.txt). It screens the compilation
# output generated by the search script, calculates match frequencies, and uses
# secure SMTP TLS pipelines to dispatch immediate HTML-formatted alerts to
# targeted recipients.
# ==============================================================================

import os
import re
import sys
import argparse
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

CONFIG_FILE = "hck_causelist_config.txt"


def load_config(path=CONFIG_FILE):
    """Parses a simple KEY = VALUE config file.
    Values may be quoted or unquoted. Lines beginning with # are ignored.
    Integer values (e.g. SMTP_PORT) are returned as int automatically."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"Config file '{path}' not found.")
    cfg = {}
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, raw = line.partition('=')
            key = key.strip()
            val = raw.strip().strip('"').strip("'")
            try:
                cfg[key] = int(val)
            except ValueError:
                cfg[key] = val
    return cfg

def verify_and_dispatch_alert(force=False):
    cfg = load_config()

    html_path      = cfg.get('HTML_OUTPUT_PATH', './causelist_search.html')
    sender         = cfg.get('SENDER_EMAIL')
    password       = cfg.get('SENDER_PASSWORD')
    receiver       = cfg.get('RECEIVER_EMAIL')
    smtp_server    = cfg.get('SMTP_SERVER', 'smtp.gmail.com')
    smtp_port      = cfg.get('SMTP_PORT', 587)
    # The config subject is a bare prefix; total_matches is appended at send time.
    subject_prefix = cfg.get('SUBJECT_TEMPLATE', '[ALERT] High Court of Karnataka Causelist Search:')

    # Guard clause to ensure essential email deployment parameters are present
    if not sender or not password or not receiver:
        print("[ERROR] Email configuration is incomplete (SENDER_EMAIL, SENDER_PASSWORD, or RECEIVER_EMAIL is missing/commented out). Aborting email dispatch.")
        return

    if not os.path.exists(html_path):
        print(f"[ERROR] Report file '{html_path}' not found.")
        return

    print(f"Reading report: {html_path}")
    with open(html_path, 'r', encoding='utf-8') as f:
        html_content = f.read()

    match_count_regex = re.search(r'Total active matches found:\s*<b>(\d+)</b>', html_content)
    total_matches = int(match_count_regex.group(1)) if match_count_regex else html_content.count('class="case-card"')

    print(f"Matches found: {total_matches}")

    if total_matches == 0:
        print("No watchlist matches found — skipping email.")
        return

    # Extract the causelist date from the HTML meta tag written by hck_causelist_search.py.
    # Include it in the subject so recipients immediately know which day's list this covers.
    date_meta = re.search(r'<meta name="causelist-date" content="([^"]+)"', html_content)
    date_display_meta = re.search(r'Causelist date: <b>([^<]+)</b>', html_content)
    causelist_date_str = date_display_meta.group(1) if date_display_meta else (
        date_meta.group(1) if date_meta else "")
    causelist_date_iso = date_meta.group(1) if date_meta else None

    # Staleness check: only email if the causelist is for a future date.
    # A causelist for today means hearings are already underway or over.
    # A causelist for a past date means the court did not publish a new one
    # (weekend, holiday) and the server is still serving the previous working
    # day's PDF — which is stale.
    # Pass --force on the command line to override this check.
    if causelist_date_iso:
        try:
            from datetime import date as _date
            cl_date = _date.fromisoformat(causelist_date_iso)
            today   = _date.today()
            if cl_date <= today and not force:
                print(f"[SKIP] Causelist date ({causelist_date_iso}) is today or in the past. "
                      f"Email suppressed. Use --force to override.")
                return
            if cl_date <= today and force:
                print(f"[FORCE] Causelist date ({causelist_date_iso}) is today or in the past, "
                      f"but --force was passed. Sending anyway.")
        except ValueError:
            print(f"[WARN] Could not parse causelist date '{causelist_date_iso}' — proceeding without staleness check.")
    else:
        print("[WARN] Causelist date not found in HTML — proceeding without staleness check.")

    if causelist_date_str and causelist_date_str != "Date unknown":
        subject = f"{subject_prefix} {causelist_date_str} — {total_matches} Tracked Matches Found"
    else:
        subject = f"{subject_prefix} {total_matches} Tracked Matches Found"

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From']    = sender
    msg['To']      = receiver
    msg.attach(MIMEText(html_content, 'html'))

    # Parse comma-separated string into a list for SMTP routing
    receiver_list = [e.strip() for e in receiver.split(",") if e.strip()] if receiver else []

    try:
        print(f"Connecting to {smtp_server}:{smtp_port}...")
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, receiver_list, msg.as_string())
        server.quit()
        print(f"[SUCCESS] Email sent to {receiver}.")
    except Exception as e:
        print(f"[ERROR] Failed to send email: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="HCK Causelist Mailer — dispatches the HTML report by email.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "By default, email is suppressed if the causelist is dated today or earlier\n"
            "(stale PDF — court did not publish a new one, or hearings already over).\n"
            "Use --force to send regardless of the causelist date."
        )
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Send email even if the causelist date is today or in the past."
    )
    args = parser.parse_args()
    verify_and_dispatch_alert(force=args.force)
